server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-2df52-100115137-9331f0f3744d.kr.lb.naverncp.com:8888"